server:
  port: 28083
  servlet:
    context-path: /jitu

spring:
  application:
    name: zyn-jitu
  profiles:
    active: @spring.profiles.active@
  config:
    import:
      - classpath:zyn-conf-common.yml
      - classpath:zyn-conf-@spring.profiles.active@.yml

zyn:
  exchange:
    services:
      jitugeoprovider: https://map-api.minedata.cn

jitu:
  geo:
    geocode-cache-ttl: 1h
    result-cache-ttl: 5m
    code-property: code
    layer-id: ${JITU_FENCE_LAYER_ID:layer-jitu}
    api-key: ${JITU_GEO_API_KEY:6b31b6fdc3d5497aaf1dcefb487aa74e}
